### ISSUE TITLE
GET RID OF HANDLEBARS MENTIONS IN YOUR SOLUTION BRANCHES

### ISSUE THREAD

**Issue by justincastilla** [SF-WDI-LABS/tunely#14]
you caused chaos in my class.

**Comment by justincastilla** [comment]
@nathanallen

**Comment by nathanallen** [comment]
Looks like it's only mentioned in the readme.

**Comment by justincastilla** [comment]
Sprint-1 doc reflects mentions of handlebars

**Comment by justincastilla** [comment]
https://github.com/SF-WDI-LABS/tunely/blob/35/solution-sprint-1/docs/sprint1.md#step-1-display-hard-coded-data

**Comment by justincastilla** [comment]
<img width="815" alt="screen shot 2017-03-10 at 11 08 09 am" src="https://cloud.githubusercontent.com/assets/4304660/23809263/e5f92c34-0581-11e7-8b11-6e4e212300fd.png">

**Comment by nathanallen** [comment]
Yes, leftover mention in readme. Actual solution code is up to date.
Replace with https://github.com/SF-WDI-LABS/tunely/blob/9db47405268b7d4ed7b410590b7c5f7952c10994/public/scripts/app.js#L9-L74 and push to all affectecd branch.

**Comment by mnfmnfm** [comment]
Cory seems to have fixed this already.
