### ISSUE TITLE
"Open index.html" is ambiguous (localhost vs. absolute file path)

### ISSUE THREAD

**Issue by nathanallen** [SF-WDI-LABS/tunely#2]

**Comment by justincastilla** [comment]
Please expand.

**Comment by nathanallen** [comment]
Directly opening `file://User/potato/path/to/tunely/index.html` will partially work since the html will render, but it will fail to load css/scripts. This is a hard bug for beginners because they do not see the difference between that and where they should be (i.e. `localhost:3000/`)

See: https://github.com/SF-WDI-LABS/tunely/blob/master/docs/sprint1.md#step-1

**Comment by nathanallen** [comment]
Fixed by b73c732066552d31932a0cfb397543b4ccfd3390
